### PR TITLE
add detect uc browser

### PR DESCRIPTION
**Pull request by dartess**

### CODE REVIEW

**Comment by gabceb** [comment]
Thanks for the PR! Can you add a test for this browser on the test files so I can merge it with your code.

**Comment by dartess** [comment]
Okay, I'm sorry. This is my first PR on github. A few days later I set UC browser on multiple devices for a complete test.

And what should I do with .min.js?

**Comment by gabceb** [comment]
Congrats on tour first PR, good job.

Dont worrry about the min file. When I merge your code I'll generate the files, bump the versions and publish on npm, etc.

**Comment by dartess** [comment]
Good. Thank you.
After changes in test.js I have to make a new PR or I can change this PR or pending merger all commit in this branch will be added to this PR?

I am sorry for my bad English. I know English is as bad as github.

**Comment by gabceb** [comment]
Any new commits on your branch will be added to the PR as long the PR is open. This is the reason why is good practice to create PRs from non-master branches (like you did) in case you want to submit multiples PRs at once.

**Comment by dartess** [comment]
It's great. Thank you again, I'm sorry for your time.

**Pull request closed without merging**
