### PR TITLE
Fix bower amd loading

### PR DESCRIPTION
**Pull request by artemkaint**

### CODE REVIEW

**Comment by le717** [comment]
@artemkaint Have you tested this in a bower environment and confirm it works?

You will need to merge with the latest `master` changes before I can merge. ;)

**Comment by artemkaint** [comment]
merged

**Comment by peter-mouland** [comment]
@artemkaint you're comment says 'merged' but the master branch says different ;)

**Comment by le717** [comment]
Merged as 1c8e69209269591d26c84173b30de1fd943a20fb. Thanks for your contribution!

**Pull request closed without merging**
