### PR TITLE
Make jQuery optional

### PR DESCRIPTION
**Pull request by le717**
@gabceb For #54.

This makes jQuery optional by exposing a new `jQBrowser` object for users to access.

* I've chosen `jQBrowser` for the global browser object as this _is_ the jQuery.browser plugin,and because I cannot think of an uncommon but descriptive name for it, for I do not want to pollute the common namespace.
*  If an UA is not provided, default to browser UA. Optionally going jQuery free, allows a new use-case for us: detecting a browser from an arbitrary UA. However, because the majority of cases will involve detecting the current browser, default to the UA if the function is called without passing parameters. When using jQuery, the UA is always provided.
* Object returned is exactly the same as when loaded through jQuery.
* The match is automatically run just as when jQuery is loaded.

### Notes ###
* Tests updates must still be devised to run the suite without jQuery, if so desired.
* README must still be updated.
* AMD/Require still requires jQuery

### CODE REVIEW

**Comment by le717** [comment]
@gabceb I think this is ready for review. I have no clue why Travis is failing, manual testing shows the `mac` key to exist and set to `true`, and I cannot get the testing stuff working on my machine. I will squash this when review is complete.

**Comment by gabceb** [comment]
Taking a look

**Comment by gabceb** [comment]
@le717 I've fixed the failing require() test and added some tests for the new stuff. Looks awesome BTW. Will merge as soon as Travis comes back

**Comment by gabceb** [comment]
This fixes #54

**Comment by le717** [comment]
> Looks awesome BTW.

Yea, I'm better at this kind of stuff than I am editing the existing regexs. ;P

**Comment by jcbvm** [comment]
Do you have any estimation when this will be released?

**Comment by le717** [comment]
I was hoping for more in the next release than this, but I've been slammed with college work. It'll try to get wordsmithing on #58 then see about a release hopefully sometime this week.

**Pull request merged**
